title: Machine learning projects
description: Collection of data science projects. Each sector takes to kaggle page where you can find the codes along with explanations and analysis.
theme: jekyll-theme-cayman
